version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    expose:
          - 3306
  back:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    expose:
      - 8080
